<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DefaultItemExcludes>$(DefaultItemExcludes);ClientApp\node_modules\**;ClientApp\dist\**</DefaultItemExcludes>
	</PropertyGroup>

	<ItemGroup>

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HomeFinancePlanner.Models\HomeFinancePlanner.Models.csproj" />
		<ProjectReference Include="..\HomeFinancePlanner.Data\HomeFinancePlanner.Data.csproj" />
		<ProjectReference Include="..\HomeFinancePlanner.Services\HomeFinancePlanner.Services.csproj" />
	</ItemGroup>

</Project>