// <auto-generated />
using System;
using HomeFinancePlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeFinancePlanner.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911040544_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("HomeFinancePlanner.Models.FinanceProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualGrossIncome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentSavings")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanTermYears")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyDebtPayments")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlySavingsContribution")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetDownPaymentPercent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FinanceProfiles");
                });

            modelBuilder.Entity("HomeFinancePlanner.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

					b.Property<int>("LotSize")
	                    .IsRequired()
                        .HasColumnType("INTEGER");

					b.Property<string>("Latitude")
						.IsRequired()
						.HasColumnType("FLOAT");

					b.Property<string>("Longitude")
						.IsRequired()
						.HasColumnType("FLOAT");

					b.HasKey("Id");

                    b.HasIndex("ZipCode");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("HomeFinancePlanner.Models.RentalListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ZipCode");

                    b.ToTable("RentalListings");
                });
#pragma warning restore 612, 618
        }
    }
}
